import assert from 'node:assert/strict';import fs from 'node:fs';
import {experimentalBacktest,bandEntries} from '../docs/experimental-engine.js';import {financeBacktest} from '../docs/finance-engine.js';import {backtest} from '../docs/engine.js';
const data=JSON.parse(fs.readFileSync('docs/data.json')),ctx=JSON.parse(fs.readFileSync('docs/research/band-overlay-context.json')),g=JSON.parse(fs.readFileSync('docs/finance-gates.json'));
for(const account of ['D','L']){const r=experimentalBacktest(data,g,0,data.dates.length,{account,overlay:'off'}),b=account==='D'?backtest(data,'D',0,data.dates.length):financeBacktest(data,g,0,data.dates.length);assert.deepEqual(r.nav,b.nav);assert.deepEqual(r.trades.map(t=>t.slice(0,account==='D'?14:16)),b.trades);}
const day=pattern=>Array.from({length:48},(_,j)=>{let c=pattern&&j===19?97:pattern&&j===20?99:100,op=pattern&&j===21?99:100;return [op,Math.max(op,c),Math.min(op,c),c,1e8,c*1e8];});
const base={dates:['2026-01-05','2026-01-06'],bars:[day(false),day(true)],close:[100,100],reference:[100,100],dividend:[0,0],bonus:[0,0],stamp:[.0005,.0005],transfer:[.00001,.00001],signals:{D:[[6,.5],[6,.5]]}};const gates={D:{all_full:[1,1]}};
assert.equal(bandEntries(base.bars[1])[21],1);
let r=experimentalBacktest(base,gates,0,2,{account:'D',overlay:'all'});assert.equal(r.trips.length,1);assert.equal(r.trips[0].entryBar,21);assert.equal(r.trips[0].exitReason,'take_profit');assert.equal(r.trades.filter(t=>t[16]===2)[0][1],22);assert(r.trips[0].complete);assert(r.trades.every(t=>t[8]>=0));
const full=structuredClone(base);full.signals.D=[[6,1],[6,1]];r=experimentalBacktest(full,gates,0,2,{account:'L',overlay:'all'});assert.equal(r.trips.length,0);assert(r.overlayBlocks.funds>0,'margincap must prevent fictitiousfreecash');
assert.equal(experimentalBacktest(base,gates,0,2,{account:'D',overlay:'gated',overlayContext:base.dates.map(date=>({date,trend20:.01,marketMA60:1}))}).trips.length,0);
const noVol=structuredClone(base);noVol.bars[1][20][4]=0;r=experimentalBacktest(noVol,gates,0,2,{account:'D',overlay:'all'});assert.equal(r.trips.length,0);
const limited=structuredClone(base);limited.bars[1][21][4]=10000;r=experimentalBacktest(limited,gates,0,2,{account:'D',overlay:'all'});let exits=r.trades.filter(t=>t[16]===2);assert.equal(exits[0][3],100);assert(exits.length>1);assert(r.trips[0].complete);
const stuck=structuredClone(base);for(let j=21;j<48;j++)stuck.bars[1][j]=[j===21?99:90,99,90,90,1e8,90e8];stuck.close[1]=90;r=experimentalBacktest(stuck,gates,0,2,{account:'D',overlay:'all'});assert.equal(r.trips.length,1);assert(!r.trips[0].complete);assert(r.trips[0].remaining>0);
const risk=structuredClone(base);risk.signals.D=[[6,1],[6,1]];risk.bars[1]=day(false);risk.bars[1][19]=[100,103,100,103,1e8,103e8];risk.bars[1][20]=[100,101,100,101,1e8,101e8];risk.bars[1][21]=[101,101,100,100,1e8,100e8];for(let j=22;j<48;j++)risk.bars[1][j]=[40,40,40,40,1e8,40e8];risk.close[1]=40;
r=experimentalBacktest(risk,gates,0,2,{account:'L',overlay:'all'});assert.equal(r.trips[0].side,-1);assert(r.trips[0].cancelled);assert.equal(r.trips[0].exitReason,'cancelled_by_base_or_risk');
for(const account of ['D','L']){const a=experimentalBacktest(data,g,0,data.dates.length,{account,overlay:'gated',overlayContext:ctx}),altered=structuredClone(data),cut=500;for(let d=cut;d<data.dates.length;d++){altered.bars[d].forEach(b=>{for(let k=0;k<4;k++)b[k]*=.98;});altered.close[d]*=.98;}const b=experimentalBacktest(altered,g,0,data.dates.length,{account,overlay:'gated',overlayContext:ctx});assert.deepEqual(a.trades.filter(t=>t[0]<cut),b.trades.filter(t=>t[0]<cut));assert.deepEqual(a.nav.slice(0,cut),b.nav.slice(0,cut));}
console.log('PASS overlay: baselineparity; completedbar timing; cashlimits; gate; zero/partial liquidity; limitdown; riskpriority; futureprefix invariance.');
